import datetime

def get_condominios():

    lista = ['EDIFICIO CONSONATA',
'CONDOMINIO G TORRES',
'CONDOMINIO SAN CARLO',
'CONDOMINIO EDIFICIO LORENZO PALACE',
'CONDOMINIO STRAUSS',
'EDIFICIO SALOMAO',
'CONDOMINIO EDIFICIO AMAZONIA',
'CONDOMINIO VICENTE LEITE',
'BLUE RESIDENCE',
'EDIFICIO ALVORADA PARK',
'CONDOMINIO PLAZA VERONNESE',
'EDIFICIO SAN LUIGI',
'CONDOMINIO PALATIUM RESIDENCIAL MEIRELES',
'CONDOMINIO EDIFICIO CLARISSE SALLES FURLANI',
'CONDOMINIO ANA MARIA',
"'CONDOMINIO EDIFICIO D'JOM'",
'EDIFICIO ABOLIÇÃO TOWER',
'CONDOMINIO EDIFICIO ALTAVISTA',
'ARTIZ MEIRELES',
'BEACH CLASS MEIRELES',
'ICON CONDOMINIUM',
'LC CORPORATE',
'CONDOMINIO PACO DO BEM',
'CONDOMINIO BOSSA NOVA']
    return lista

def round_to_quarter():
    t = datetime.datetime.now()
    # Arredonda os minutos para baixo ao múltiplo de 15 mais próximo
    rounded_minutes = (t.minute // 15) * 15
    return t.replace(minute=rounded_minutes, second=0, microsecond=0)